### ISSUE TITLE
Null pointer Exception at 'int de.blox.graphview.tree.BuchheimWalkerNodeData.getDepth()'

### ISSUE THREAD

**Issue by VKdeveloper** [Team-Blox/TreeView#39]
Following is the code used:

```
GraphView graphView = findViewById(R.id.graph);
List<Parent> parent_list = response.body();
Graph graph = new Graph();
    for(int h = 0; h < parent_list.size();h++) {
            Node node1 = new Node(parent_list.get(h).name);
            Node node2 = new Node(parent_list.get(h).user_id);
            graph.addEdge(node1, node2);
      }
final BaseGraphAdapter<ViewHolder> adapter = new BaseGraphAdapter<ViewHolder>(graph) {

            @NonNull
            @Override
            public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                final View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.node, parent, false);
                return new SimpleViewHolder(view);
            }

            @Override
            public void onBindViewHolder(ViewHolder viewHolder, Object data, int position) {
                ((SimpleViewHolder)viewHolder).textView.setText(data.toString());
            }
        };
        graphView.setAdapter(adapter);

        // set the algorithm here
        final BuchheimWalkerConfiguration configuration = new BuchheimWalkerConfiguration.Builder()
                .setSiblingSeparation(100)
                .setLevelSeparation(300)
                .setSubtreeSeparation(300)
                .setOrientation(BuchheimWalkerConfiguration.ORIENTATION_TOP_BOTTOM)
                .build();
        adapter.setAlgorithm(new BuchheimWalkerAlgorithm(configuration));
```
 

How to fix this issue ? As the graphview loads correctly without using for loop.

**Comment by DennisBlock** [comment]
As you noticed correctly if you use the foor loop as it is right now it's not going to work. This is because you're buiding your graph the wrong way. Right now all you have is "multiple trees", each with only two nodes, and the algorithm can't handle that. I don't know your data structure, but you need to change the way you create your graph. Create a parent node, iterate over its children and add them to the graph. Choose a new parent and do the same. Hope this helps!

**Comment by VKdeveloper** [comment]
Let me try this

**Comment by VKdeveloper** [comment]
![error_1](https://user-images.githubusercontent.com/7613277/57693432-d7c0f680-7666-11e9-9943-21c572b1a4bc.png)
![error_2](https://user-images.githubusercontent.com/7613277/57693622-4a31d680-7667-11e9-8105-ebe93cca02d7.png)

@DennisBlock Now im using following code :
```
Graph graph = new Graph();
final Node node1 = new Node("Parent");
graph.addNode(node1);
//child_list = all children's for node1 
for(int h = 0; h < child_list.size();h++) {
final Node node_child = new Node(child_list.get(h));
graph.addEdge(node1, node_child);
}
```
//After this set adapter and adapter algorithm.

DATABASE STRUCTURE

```
ID  PARENT_ID    NAME
1                PARENT
2        1       CHILD
3        1       CHILD
4        1       CHILD
```

The application crashes saying `java.lang.StackOverflowError: stack size 8MB`

**Comment by DennisBlock** [comment]
Is this the only code you used for building the graph? It looks right, but the exception indicates that you have a loop in your tree, eg. node1->child->node1.

**Comment by VKdeveloper** [comment]
@DennisBlock can you suggest how it is needed to code ?

MY DATABASE STRUCTURE

```
ID  PARENT_ID    NAME
1                JACK WILSON
2        1       GEORGE WILSON
3        1       JOHN WILSON
4        1       ELIGIUS WILSON
5        2       GRATIN WILSON
6        3       OSMUND WILSON
7        6       MARK WILSON
```

**Comment by DennisBlock** [comment]
You could do something like this with recursion:
```
Graph graph = // ...
Node root = // find root, this would be the row without a PARENT_ID
addChildren(graph, root);

void addChildren(Graph graph, Node node) {
    List<Row> children = // find children of node (assume Row is your db data structure)
    if (children.isEmpty()) return;

    for (iterate over children) {
        Node child = // create child
        graph.addEdge(node, child);

        addChildren(graph, child)
    }
}
```
This is not tested, but it should give you an idea how this could be done.

**Comment by VKdeveloper** [comment]
@DennisBlock Thank you very much for penning down the needful code.

I tested the above code and it worked correctly at very first attempt without any error.

**Few questions about Tree Layout:**
1) How many child relations can a single parent hold ? What is maximum no of nodes that can be created ? 
Reason : I have over 1000+ records in my database with similar data structure. Application crashes at this point while it works correctly for some tables with small no of records.

2) How to clear the existing loaded Tree Layout ? 
Reason : It was observed once a Tree Layout is created, and re-called to draw a new one(data from different table) application crashes while it works for every first attempt for each table.
  
3) Zoom Issue
Reason: More bulky the hierarchy, it is difficult to read names as we cannot zoom efficiently.  

![ss](https://user-images.githubusercontent.com/7613277/57736981-9ca2df80-76c7-11e9-93cf-6b3c22acc15c.png)

**Comment by DennisBlock** [comment]
To answer you questions:

1. A node can have (theoretically) an infinite number of children. But at this point in time this library is not efficient enough to handle such a high number of nodes. Not because of the graph structure itself, but mostly because each node creates a view that needs to be rendered and displayed. Thats simply to much for android. We have to implement some sort of recycling of the views. But if the whole graph should be displayed the recycling of views doesn't matter anymore. So for big graphs we need to prevent to show the whole graph or come up with a different solution. One another point is, that for big graphs the algorithms taking too much time and blocking the ui thread. I think you noticed this for your graph in the picture.

2. The easiest way to do this, is to create a new graph and set it with the adapters `GraphAdapter.setGraph( Graph)` method. 

3. What do you mean you can't zoom efficiently? You can't zoom in enough to read the text? You can change the min and max zoom in the xml (`minZoom` and `maxZoom`) or programmatically (`setMinZoom(Float)` and `setMaxZoom(float)`)

**Comment by GregorBlock** [comment]
I'm closing this because of inactivity. Please re-open if you want to add something to this issue.

**Comment by abhishekjalu** [comment]
Hi ,
I have a following type response . Please tell me how to code the Graph for this . I am getting this error

 java.lang.StackOverflowError: stack size 8MB
        at de.blox.graphview.Graph.successorsOf(Graph.java:250)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.isLeaf(BuchheimWalkerAlgorithm.java:297)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:75)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)



===============MY API REQUEST IS OF THIS FORM========
{
    "status": 0,
    "success": [
        {
            "name": "Mukesh jha ",
            "member_id": "2019062601",
            "parent_id": "2019060501"
        },
        {
            "name": "Prem kumar",
            "member_id": "2019062608",
            "parent_id": "2019060501"
        },
        {
            "name": "Janvi jha",
            "member_id": "2019062609",
            "parent_id": "2019060501"
        },
        {
            "name": "Danvir saw",
            "member_id": "2019062602",
            "parent_id": "2019062601"
        },
        {
            "name": "danvir saw",
            "member_id": "2019062603",
            "parent_id": "2019062602"
        },
        {
            "name": "danvir saw",
            "member_id": "2019062604",
            "parent_id": "2019062602"
        },
        {
            "name": "danvir saw",
            "member_id": "2019062605",
            "parent_id": "2019062602"
        },
        {
            "name": "danvir saw",
            "member_id": "2019062606",
            "parent_id": "2019062603"
        },
        {
            "name": "Pankaj prajapati ",
            "member_id": "2019062607",
            "parent_id": "2019062601"
        },
        {
            "name": "rohit",
            "member_id": "2019062610",
            "parent_id": "2019062609"
        },
        {
            "name": "Anuradha kumari",
            "member_id": "2019062701",
            "parent_id": "2019062603"
        },
        {
            "name": "Anuradha kumari",
            "member_id": "2019062702",
            "parent_id": "2019062701"
        },
        {
            "name": "Anuradha kumari",
            "member_id": "2019062703",
            "parent_id": "2019062701"
        },
        {
            "name": "Anuradha kumari",
            "member_id": "2019062704",
            "parent_id": "2019062701"
        },
        {
            "name": "Anuradha kumari",
            "member_id": "2019062705",
            "parent_id": "2019062702"
        },
        {
            "name": "Abhishek kumar",
            "member_id": "2019062706",
            "parent_id": "2019062702"
        },
        {
            "name": "Vishnu pandey",
            "member_id": "2019062707",
            "parent_id": "2019062702"
        },
        {
            "name": "Niraj kumar",
            "member_id": "2019062708",
            "parent_id": "2019062705"
        },
        {
            "name": "Utkarsh sharam",
            "member_id": "2019062709",
            "parent_id": "2019062705"
        },
        {
            "name": "lal bahadur saw",
            "member_id": "2019062710",
            "parent_id": "2019062603"
        },
        {
            "name": "laxmi kumari goswami",
            "member_id": "2019062711",
            "parent_id": "2019062606"
        },
        {
            "name": "vedprakassh mishra",
            "member_id": "2019062712",
            "parent_id": "2019062606"
        },
        {
            "name": "Neha kumari",
            "member_id": "2019062713",
            "parent_id": "2019062711"
        },
        {
            "name": "Gopi Kumar mahato",
            "member_id": "2019062714",
            "parent_id": "2019062710"
        },
        {
            "name": "anjita kumari",
            "member_id": "2019062801",
            "parent_id": "2019062714"
        },
        {
            "name": "shishan kumar",
            "member_id": "2019062802",
            "parent_id": "2019062801"
        },
        {
            "name": "shivam raj gupata",
            "member_id": "2019062803",
            "parent_id": "2019062604"
        },
        {
            "name": "om prakash gupta",
            "member_id": "2019062804",
            "parent_id": "2019062604"
        },
        {
            "name": "Roshni kumari",
            "member_id": "2019063001",
            "parent_id": "2019062609"
        },
        {
            "name": "Ritu kumari",
            "member_id": "2019070101",
            "parent_id": "2019062604"
        },
        {
            "name": "Ritu kumari",
            "member_id": "2019070102",
            "parent_id": "2019070101"
        },
        {
            "name": "Ritu kumari",
            "member_id": "2019070103",
            "parent_id": "2019070101"
        },
        {
            "name": "Ritu kumari",
            "member_id": "2019070104",
            "parent_id": "2019070101"
        },
        {
            "name": "Ritu kumari",
            "member_id": "2019070105",
            "parent_id": "2019070102"
        },
        {
            "name": "Priya kumari",
            "member_id": "2019070106",
            "parent_id": "2019062713"
        }
    ]
}

**Comment by DennisBlock** [comment]
This exception indicates, that you have a loop in your graph, whicht can't be handled by the tree algorithm. 
Your problem seems to be here (didn't read all of the api response, so there might be another loop)
```
"success": [
{
"name": "Mukesh jha ",
"member_id": "2019062601",
"parent_id": "2019060501"
}, // ...
```
Your item has itself as a parent, which creates a loop. Remove it and it should be working.

Just a side note: Please don't post in already closed issues. Even if you have the same problem as this one, but can't figure it out, open a new issue for better visibility.
