### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 4000000008 byte allocation with 16777216 free bytes and 167MB until OOM

### ISSUE THREAD

**Issue by abhishekjalu** [Team-Blox/TreeView#48]
I have json response with ParentId and memberId . I want to draw the member graph. Please help me to find the solution . Getting following ERROR.:

D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.draw.hierarchyloginregistrationpages, PID: 20459
    java.lang.OutOfMemoryError: Failed to allocate a 4000000008 byte allocation with 16777216 free bytes and 167MB until OOM
        at com.draw.hierarchyloginregistrationpages.Pages.MemberGraph2.onCreate(MemberGraph2.java:45)
        at android.app.Activity.performCreate(Activity.java:6303)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
        at android.app.ActivityThread.access$1000(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:5527)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
E/MQSEventManagerDelegate: failed to get MQSService.
I/Process: Sending signal. PID: 20459 SIG: 9
Application terminated.

*************************** DONT HAVE ANY LOOP IN THE DATA ***********************

Please give some code snippet. Thanks in Advance

[values.txt](https://github.com/Team-Blox/GraphView/files/3393959/values.txt)

**Comment by DennisBlock** [comment]
> *************************** DONT HAVE ANY LOOP IN THE DATA ***********************

Either you have some code loop, which can't terminate so you ran out of memory (hence the OOM exception) or you do have a loop in your data. ~~As mentioned in the other issue your first item is a parent of itself. Which, in my opinion, creates a loop.~~ 

```
"name": "Mukesh jha ",
"member_id": "2019062601",
"parent_id": "2019060501"
```
~~`member_id` and `parent_id` are the same. I don't know how you create your graph/nodes but the issue would be here!~~

Edit: Forget all of what I said. I, lazily, compared only the first few and last digits and assumed it would be the same. Sorry for that. 

Could you post more code, especially what on line MemberGraph2.java:45?

**Comment by GregorBlock** [comment]
I'm closing this because of inactivity. Please re-open if you want to add something to this issue.
