### ISSUE TITLE
getHeight()' on a null object reference

### ISSUE THREAD

**Issue by DevMensIT** [Team-Blox/TreeView#65]
Hey there i want to know what is limit of graph? i have more than 5k records with nodes. 
i need help to solve this.

java.lang.NullPointerException: Attempt to invoke virtual method 'int de.blox.graphview.Size.getHeight()' on a null object reference
        at de.blox.graphview.Node.getHeight(Node.java:45)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:69)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:89)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.run(BuchheimWalkerAlgorithm.java:345)
        at de.blox.graphview.BaseGraphAdapter.notifySizeChanged(BaseGraphAdapter.java:41)
        at de.blox.graphview.GraphNodeContainerView.onMeasure(GraphNodeContainerView.java:367)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChild(ViewGroup.java:6799)
        at android.view.ViewGroup.measureChildren(ViewGroup.java:6776)
        at com.otaliastudios.zoom.ZoomLayout.onMeasure(ZoomLayout.java:104)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
        at android.view.View.measure(View.java:24549)
        at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:401)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3007)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1834)
2020-03-19 23:40:57.893 27200-27200/com.kishanmaniar.treeview E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2123)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1722)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7605)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:852)
        at android.view.Choreographer.doFrame(Choreographer.java:787)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by GregorBlock** [comment]
Hi, so 5k nodes are definitely too much for GraphView as it is not yet optimized for it. Which version do you use? Actually there should be no npe at this place.

**Comment by DevMensIT** [comment]
is there any alternative option ? what max node size ? i'm really looking for this but now i'm stuck here
version using : 0.4.2
really i need your help.

**Comment by GregorBlock** [comment]
Well there is already a newer version 0.6.1. I would suggest you try again with an update. Unfortunately it is not possible to draw so many nodes at the same time with the current approach.

**Comment by DevMensIT** [comment]
okay I'll try after update and notify you. but what's max limit or the graph ?

**Comment by GregorBlock** [comment]
In theory, there is no limit. It depends on how complex you design the nodes View and the runtime of the chosen algorithm.

**Comment by DevMensIT** [comment]
hey i updated version and now im getting this error.
algorithm : BuchheimWalkerAlgorithm

java.lang.StackOverflowError: stack size 8192KB
        at java.util.ArrayList.grow(ArrayList.java:275)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
        at java.util.ArrayList.add(ArrayList.java:467)
        at de.blox.graphview.Graph.predecessorsOf(Graph.java:282)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.hasLeftSibling(BuchheimWalkerAlgorithm.java:312)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:78)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
2020-03-21 20:24:50.282 24823-24823/com.kishanmaniar.treeview E/AndroidRuntime:     at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
2020-03-21 20:24:50.331 24823-24836/com.kishanmaniar.treeview I/maniar.treevie: Background young concurrent copying GC freed 60390(2536KB) AllocSpace objects, 1(804KB) LOS objects, 0% free, 18MB/18MB, paused 89us total 105.910ms
2020-03-21 20:24:50.522 24823-24823/com.kishanmaniar.treeview I/chatty: uid=10036(com.kishanmaniar.treeview) identical 1215 lines
2020-03-21 20:24:50.522 24823-24823/com.kishanmaniar.treeview E/AndroidRuntime:     at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
2020-03-21 20:24:50.523 24823-24823/com.kishanmaniar.treeview E/AndroidRuntime:     at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.firstWalk(BuchheimWalkerAlgorithm.java:90)
        at de.blox.graphview.tree.BuchheimWalkerAlgorithm.run(BuchheimWalkerAlgorithm.java:363)
        at de.blox.graphview.BaseGraphAdapter.notifySizeChanged(BaseGraphAdapter.java:29)
        at de.blox.graphview.GraphNodeContainerView.onMeasure(GraphNodeContainerView.java:368)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChild(ViewGroup.java:6799)
        at android.view.ViewGroup.measureChildren(ViewGroup.java:6776)
        at com.otaliastudios.zoom.ZoomLayout.onMeasure(ZoomLayout.kt:129)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
        at android.view.View.measure(View.java:24549)
        at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
2020-03-21 20:24:50.523 24823-24823/com.kishanmaniar.treeview E/AndroidRuntime:     at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:401)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3007)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1834)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2123)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1722)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7605)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:852)
        at android.view.Choreographer.doFrame(Choreographer.java:787)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by GregorBlock** [comment]
Stackoverflow can be an indicator that you have a loop in your structure. It could be something else without having more information.

**Comment by DevMensIT** [comment]
yes. i have loop and I'm using hashmap to store nodes. 
please help me to find a way.

**Comment by GregorBlock** [comment]
BuchheimWalker does not support loops because it was developed for tree structures. You could use the Sugiyama for this.

**Comment by DevMensIT** [comment]
I'm not using algorithm inside loop but i used loop for create nodes only. algorithm is outside the loop. 


i will check that and will notify you. thank you.

**Comment by GregorBlock** [comment]
No, I meant a loop in your data structure, 

for example: a -> b -> c -> a (loop here)

**Comment by DevMensIT** [comment]
actually my first loop here

```
 final Graph graph = new Graph();
        loop(){
final Node node1 = new Node(getNodeText());
}
```



first loop to create all nodes.

2. Loop for create .addEdge


```
loop(){
graph.addEdge(node1, node2);
}

```

**Comment by DennisBlock** [comment]
@GregorBlock didn't mean your loop statements. He is talking about a loop or [cycle (in graph theory)](https://en.wikipedia.org/wiki/Cycle_(graph_theory)) in your graph.

**Comment by DevMensIT** [comment]
i will try Sugiyama. hope it will help.

**Comment by DevMensIT** [comment]
i tried to use SugiyamaAlgorithm but everything is getting messup. checkout 
![Screenshot_20200326-210617](https://user-images.githubusercontent.com/11617013/77665532-d0b48580-6fa5-11ea-8387-753540ce8ed7.png)

BuchheimWalker algorithm only can help me but i not able to find why its getting crash.
and my loop structure is also well.

**Comment by GregorBlock** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
