### ISSUE TITLE
With the huge level of data(children within children) I'm getting the Android Runtime error

### ISSUE THREAD

**Issue by sallu5274** [Team-Blox/TreeView#85]
at dev.bandb.graphview.layouts.tree.BuchheimWalkerLayoutManager.firstWalk(BuchheimWalkerLayoutManager.kt:67)
at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4182)
                                                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2759)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3086)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:882)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	
  This is coming while adding graph object to the view, for small set of data its working fine but every time I'm trying to set it up for huge amount of data its getting ANR and getting crashed with the mentioned error. 
  
 Can you help me with this thing?

**Comment by GregorBlock** [comment]
Hi @sallu5274, the current design makes it practically impossible to render large graphs in our opinion.
Also simply the runtime of the layout algorithms running locally on the device is also a bottleneck issue for displaying large graphs.
